// JT-ZERO v45.2: exact-replay-based offline multi-model analysis of v44 master CSV.
// Starts at the real post-calibration boundary and uses v44 recorded startup semantics.

#include <Eigen/Dense>
#include <Eigen/Geometry>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <numeric>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace {
constexpr double G=9.81, CX=0.014570, CY=0.082383, PI=3.14159265358979323846;
struct Row{std::string stage;uint64_t us=0;double dt=0;Eigen::Vector3d a=Eigen::Vector3d::Zero(),w=Eigen::Vector3d::Zero(),wf=Eigen::Vector3d::Zero(),af=Eigen::Vector3d::Zero(),vf=Eigen::Vector3d::Zero();Eigen::Matrix3d Rf=Eigen::Matrix3d::Identity();};
struct Model{std::string name;int mode=0;double tau=0;};
struct Res{std::string name;double final_ang=0,final_axy=0,ep_rms=0,ep_max=0,static_abs_dv=0;};
std::vector<std::string> sp(const std::string&s){std::vector<std::string>v;std::stringstream q(s);std::string x;while(std::getline(q,x,','))v.push_back(x);return v;}
double D(const std::string&s){return s.empty()?0:std::stod(s);}
Eigen::Matrix3d ex(const Eigen::Vector3d&q){double a=q.norm();return a<1e-12?Eigen::Matrix3d::Identity():Eigen::AngleAxisd(a,q/a).toRotationMatrix();}
double ang(const Eigen::Vector3d&a,const Eigen::Vector3d&b){double c=a.normalized().dot(b.normalized());c=std::clamp(c,-1.0,1.0);return std::acos(c)*180/PI;}
Eigen::Matrix3d rpy(double r,double p,double y){r*=PI/180;p*=PI/180;y*=PI/180;return Eigen::AngleAxisd(r,Eigen::Vector3d::UnitX()).toRotationMatrix()*Eigen::AngleAxisd(p,Eigen::Vector3d::UnitY()).toRotationMatrix()*Eigen::AngleAxisd(y,Eigen::Vector3d::UnitZ()).toRotationMatrix();}
std::vector<Row> load(const std::string&p){std::ifstream f(p);if(!f)throw std::runtime_error("cannot open "+p);std::string l;std::getline(f,l);auto h=sp(l);std::map<std::string,int>c;for(int i=0;i<(int)h.size();++i)c[h[i]]=i;const char* n[]={"stage","imu_us","dt","flu_ax","flu_ay","flu_az","raw_gx","raw_gy","raw_gz","fixed_gx","fixed_gy","fixed_gz","fixed_R_roll","fixed_R_pitch","fixed_R_yaw","fixed_aw_x","fixed_aw_y","fixed_aw_z","fixed_vx","fixed_vy","fixed_vz"};for(auto x:n)if(!c.count(x))throw std::runtime_error(std::string("missing ")+x);std::vector<Row>v;while(std::getline(f,l)){auto x=sp(l);if(x.size()<h.size())continue;Row z;z.stage=x[c["stage"]];z.us=std::stoull(x[c["imu_us"]]);z.dt=D(x[c["dt"]]);z.a={D(x[c["flu_ax"]]),D(x[c["flu_ay"]]),D(x[c["flu_az"]])};z.w={D(x[c["raw_gx"]]),D(x[c["raw_gy"]]),D(x[c["raw_gz"]])};z.wf={D(x[c["fixed_gx"]]),D(x[c["fixed_gy"]]),D(x[c["fixed_gz"]])};z.Rf=rpy(D(x[c["fixed_R_roll"]]),D(x[c["fixed_R_pitch"]]),D(x[c["fixed_R_yaw"]]));z.af={D(x[c["fixed_aw_x"]]),D(x[c["fixed_aw_y"]]),D(x[c["fixed_aw_z"]])};z.vf={D(x[c["fixed_vx"]]),D(x[c["fixed_vy"]]),D(x[c["fixed_vz"]])};v.push_back(z);}return v;}
std::vector<bool> mask(const std::vector<Row>&v,size_t s){const int H=100;std::vector<bool>m(v.size());std::vector<Eigen::Vector3d>pa(v.size()+1),pw(v.size()+1),pa2(v.size()+1),pw2(v.size()+1);for(size_t i=s;i<v.size();++i){pa[i+1]=pa[i]+v[i].a;pw[i+1]=pw[i]+v[i].w;pa2[i+1]=pa2[i]+v[i].a.cwiseProduct(v[i].a);pw2[i+1]=pw2[i]+v[i].w.cwiseProduct(v[i].w);}for(size_t i=s+H;i+H<v.size();++i){size_t b=i-H,e=i+H;double n=double(e-b);Eigen::Vector3d a=((pa[e]-pa[b])/n).eval();Eigen::Vector3d w=((pw[e]-pw[b])/n).eval();Eigen::Vector3d va=((pa2[e]-pa2[b])/n-a.cwiseProduct(a)).eval();Eigen::Vector3d vw=((pw2[e]-pw2[b])/n-w.cwiseProduct(w)).eval();double as=std::sqrt(std::max(0.0,va.sum())),ws=std::sqrt(std::max(0.0,vw.sum()));if(ws<.003&&as<.16&&std::abs(a.norm()-G)<.30)m[i]=true;}return m;}
Res run(const std::vector<Row>&v,size_t s,const std::vector<bool>&sm,const Eigen::Vector3d&ba,const Model&M){Res z;z.name=M.name;Eigen::Matrix3d R=v[s].Rf;Eigen::Vector3d b=Eigen::Vector3d::Zero();std::vector<double>ep;std::string prevStage=v[s].stage;for(size_t i=s+1;i<v.size();++i){double dt=(v[i].dt>0&&v[i].dt<.03)?v[i].dt:0;Eigen::Vector3d w=v[i].w-b;w.x()+=CX*w.z();w.y()+=CY*w.z();if(dt)R=R*ex(w*dt);Eigen::Vector3d aw=R*(v[i].a-ba)+Eigen::Vector3d(0,0,G);if(sm[i]&&dt)z.static_abs_dv+=aw.head<2>().norm()*dt;if(sm[i]&&dt&&M.mode){double al=1-std::exp(-dt/M.tau);if(M.mode==1)b.x()+=al*(v[i].w.x()-b.x());else if(M.mode==2){b.x()+=al*(v[i].w.x()-b.x());b.y()+=al*(v[i].w.y()-b.y());}else b+=al*(v[i].w-b);}if(v[i].stage!=prevStage){size_t k=i-1,b0=k,n=0;Eigen::Vector3d ma=Eigen::Vector3d::Zero();while(b0>s&&v[b0-1].stage==prevStage&&sm[b0-1])--b0;for(size_t q=b0;q<=k;++q)if(sm[q]){ma+=v[q].a-ba;++n;}if(n>100){ma/=double(n);ep.push_back(ang(R.transpose()*Eigen::Vector3d(0,0,-1),ma));}prevStage=v[i].stage;}}
 Eigen::Vector3d ma=Eigen::Vector3d::Zero();size_t n=0;for(size_t i=s;i<v.size();++i)if(sm[i]&&v[i].stage=="FINAL_STATIC"){ma+=v[i].a-ba;++n;}if(n){ma/=double(n);z.final_ang=ang(R.transpose()*Eigen::Vector3d(0,0,-1),ma);z.final_axy=(R*ma+Eigen::Vector3d(0,0,G)).head<2>().norm();}double ss=0;for(double x:ep){ss+=x*x;z.ep_max=std::max(z.ep_max,x);}if(!ep.empty())z.ep_rms=std::sqrt(ss/ep.size());return z;}
}
int main(int ac,char**av){std::string p=ac>1?av[1]:"/home/vio/jtzero_imu_master_v44.csv",op=ac>2?av[2]:"/home/vio/jtzero_imu_models_v45_2.txt";try{auto v=load(p);size_t s=0;while(s<v.size()&&v[s].stage=="CALIB_STATIC")++s;if(s>=v.size())throw std::runtime_error("no post-cal boundary");Eigen::Vector3d ba=Eigen::Vector3d::Zero();size_t bn=0;for(size_t i=s;i<v.size();++i){Eigen::Vector3d q=v[i].a-v[i].Rf.transpose()*(v[i].af-Eigen::Vector3d(0,0,G));ba+=q;++bn;if(bn>=2000)break;}ba/=double(bn);auto sm=mask(v,s);std::vector<Model>mm={{"CONST_BG+ZXY",0,1},{"BG_X tau1",1,1},{"BG_X tau2",1,2},{"BG_X tau5",1,5},{"BG_X tau10",1,10},{"BG_XY tau5",2,5},{"BG_XYZ tau5",3,5}};std::vector<Res>rr;for(auto&m:mm)rr.push_back(run(v,s,sm,ba,m));std::ostringstream o;o<<std::fixed<<std::setprecision(6);o<<"============================================================\nJT-ZERO v45.2 EXACT-SEMANTICS MODEL COMPARISON\n============================================================\ninput: "<<p<<"\nrows: "<<v.size()<<"\npost-cal boundary: "<<s<<" stage="<<v[s].stage<<"\ninferred BA: ["<<ba.transpose()<<"]\nstatic samples post-cal: "<<std::count(sm.begin()+s,sm.end(),true)<<"\n\nBASELINE REPLAY SANITY\nrecorded final FIXED Vxy: "<<v.back().vf.head<2>().norm()<<" m/s\nrecorded final FIXED axy: "<<v.back().af.head<2>().norm()<<" m/s^2\n\nMODEL COMPARISON\nmodel | final_gravity_deg | final_static_axy | endpoint_rms | endpoint_max | static_abs_dv\n";for(auto&r:rr)o<<r.name<<" | "<<r.final_ang<<" | "<<r.final_axy<<" | "<<r.ep_rms<<" | "<<r.ep_max<<" | "<<r.static_abs_dv<<"\n";o<<"\nDECISION RULES\n- CONST is the valid v44-semantics reference.\n- Bias adaptation is supported only if improvement appears in final angle AND endpoint metrics.\n- X-only vs XY/XYZ separates dominant X drift from general bias drift.\n- v42 Z->XY coefficients remain fixed in every model; this analysis does not refit them.\n";std::ofstream f(op);f<<o.str();std::cout<<o.str()<<"\nResult TXT: "<<op<<"\n";}catch(const std::exception&e){std::cerr<<"[FATAL] "<<e.what()<<"\n";return 1;}}
