// JT-ZERO v15.47 offline diagnostic: compare observed planar homography with
// the closest pure camera rotation. Dataset v15.42 only; production untouched.
#include <opencv2/opencv.hpp>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <string>
#include <vector>

namespace {
constexpr int64_t CAM_PERIOD_NS=30000000LL;
constexpr int64_t RAW_MAX_DT_NS=20000000LL;
constexpr double PI=3.14159265358979323846;
struct Cam{uint32_t seq=0;int64_t ts=0;uint64_t off=0;size_t bytes=0;};
struct Att{int64_t ts=0;double r=0,p=0,y=0,ys=0;};
struct M{double raw=0,fc=0,best=0,herr=0,hin=0,fcrot=0,bestrot=0;int n=0;};
std::vector<std::string> split(const std::string&s){std::vector<std::string>o;std::string c;for(char ch:s){if(ch==','){o.push_back(c);c.clear();}else c.push_back(ch);}o.push_back(c);return o;}
double dv(const std::string&s){return s.empty()?0.0:std::stod(s);} long long iv(const std::string&s){return s.empty()?0:std::stoll(s);}
double med(std::vector<double>v){if(v.empty())return NAN;size_t n=v.size(),k=n/2;std::nth_element(v.begin(),v.begin()+k,v.end());double a=v[k];if(n&1)return a;std::nth_element(v.begin(),v.begin()+k-1,v.end());return .5*(a+v[k-1]);}
std::vector<Cam> loadCam(const std::string&p){std::ifstream f(p);if(!f)throw std::runtime_error("camera csv");std::string l;std::getline(f,l);std::vector<Cam>o;bool have=false;uint32_t ps=0;int64_t pt=0,last=0;while(std::getline(f,l)){auto c=split(l);if(c.size()<7)continue;Cam x;x.seq=(uint32_t)std::stoul(c[0]);x.ts=iv(c[2]);x.off=(uint64_t)std::stoull(c[5]);x.bytes=(size_t)std::stoull(c[6]);bool ok=true;if(have){auto dt=x.ts-pt;ok=x.seq==ps+1&&dt>0&&dt<=RAW_MAX_DT_NS;}have=true;ps=x.seq;pt=x.ts;bool due=last==0||x.ts-last>=CAM_PERIOD_NS;if(ok&&due&&x.bytes){o.push_back(x);last=x.ts;}}return o;}
std::vector<Att> loadAtt(const std::string&p){std::ifstream f(p);if(!f)throw std::runtime_error("att csv");std::string l;std::getline(f,l);auto h=split(l);auto ix=[&](const std::string&n){auto i=std::find(h.begin(),h.end(),n);if(i==h.end())throw std::runtime_error("missing "+n);return size_t(i-h.begin());};size_t it=ix("mapped_rpi_ns"),ir=ix("roll_deg"),ip=ix("pitch_deg"),iy=ix("yaw_deg"),iys=ix("yawspeed");std::vector<Att>o;while(std::getline(f,l)){auto c=split(l);if(c.size()<=std::max({it,ir,ip,iy,iys}))continue;Att a{iv(c[it]),dv(c[ir]),dv(c[ip]),dv(c[iy]),dv(c[iys])};if(a.ts>0)o.push_back(a);}return o;}
const Att& near(const std::vector<Att>&a,int64_t t,size_t&k){while(k+1<a.size()&&std::llabs(a[k+1].ts-t)<=std::llabs(a[k].ts-t))++k;return a[k];}
cv::Mat gray(std::ifstream&f,const Cam&c){std::vector<uchar>b(c.bytes);f.clear();f.seekg((std::streamoff)c.off);f.read((char*)b.data(),c.bytes);if((size_t)f.gcount()!=c.bytes)return{};return cv::imdecode(b,cv::IMREAD_GRAYSCALE);}
cv::Matx33d rpy(double r,double p,double y){r*=PI/180;p*=PI/180;y*=PI/180;double cr=cos(r),sr=sin(r),cp=cos(p),sp=sin(p),cy=cos(y),sy=sin(y);return {cy*cp,cy*sp*sr-sy*cr,cy*sp*cr+sy*sr,sy*cp,sy*sp*sr+cy*cr,sy*sp*cr-cy*sr,-sp,cp*sr,cp*cr};}
double angle(const cv::Mat&R){double tr=R.at<double>(0,0)+R.at<double>(1,1)+R.at<double>(2,2);double c=std::clamp((tr-1)*.5,-1.0,1.0);return acos(c)*180/PI;}
cv::Mat closestRotation(const cv::Mat&Hn){double d=cv::determinant(Hn);double s=(std::abs(d)>1e-12)?std::cbrt(std::abs(d)):1.0;cv::Mat A=Hn/s;cv::SVD svd(A,cv::SVD::FULL_UV);cv::Mat U=svd.u,Vt=svd.vt,R=U*Vt;if(cv::determinant(R)<0){U.col(2)*=-1;R=U*Vt;}return R;}
double reprojMed(const std::vector<cv::Point2f>&a,const std::vector<cv::Point2f>&b,const cv::Mat&H,const cv::Mat&mask=cv::Mat()){std::vector<cv::Point2f>p;cv::perspectiveTransform(a,p,H);std::vector<double>e;for(size_t i=0;i<p.size();++i){if(!mask.empty()&&!mask.at<uchar>((int)i))continue;e.push_back(cv::norm(p[i]-b[i]));}return med(e);}
void sum(const char*n,const std::vector<M>&v){std::vector<double>raw,fc,best,he,hi,fr,br;for(auto&m:v){raw.push_back(m.raw);fc.push_back(m.fc);best.push_back(m.best);he.push_back(m.herr);hi.push_back(m.hin);fr.push_back(m.fcrot);br.push_back(m.bestrot);}std::cout<<n<<" pairs="<<v.size();if(v.empty()){std::cout<<"\n";return;}std::cout<<std::fixed<<std::setprecision(3)<<" raw="<<med(raw)<<"px FCrot_res="<<med(fc)<<"px BESTrot_res="<<med(best)<<"px H_err="<<med(he)<<"px H_inlier="<<med(hi)<<" FC_rot="<<med(fr)<<"deg BEST_rot="<<med(br)<<"deg\n";}
}
int main(int argc,char**argv){std::string cp=argc>1?argv[1]:"/home/vio/jtzero_yaw_only_v15_42_camera.csv",mp=argc>2?argv[2]:"/home/vio/jtzero_yaw_only_v15_42.mjpg",ap=argc>3?argv[3]:"/home/vio/jtzero_yaw_only_v15_42_attitude.csv",op=argc>4?argv[4]:"/home/vio/jtzero_homography_purerot_v15_47.csv";try{auto C=loadCam(cp);auto A=loadAtt(ap);std::ifstream jf(mp,std::ios::binary);if(C.size()<2||A.empty()||!jf)throw std::runtime_error("input");cv::Mat K=(cv::Mat_<double>(3,3)<<568.53170752165227,0,315.98271077441063,0,569.68005562865858,239.88148589100641,0,0,1),Ki=K.inv();cv::Mat D=(cv::Mat_<double>(1,5)<<0.073569192194028493,-0.095253893789117,-0.010810530757187299,-0.0022843373576970235,0.082177400802757483);cv::Matx33d RBC(0.009367371,0.999954838,-0.001604448,0.999326771,-0.009418381,-0.035458408,-0.035471918,-0.001271215,-0.999369865);std::ofstream out(op);out<<"t0_ns,t1_ns,rotating,tracks,raw_px,fc_rot_res_px,best_rot_res_px,h_err_px,h_inlier,fc_rot_deg,best_rot_deg\n";cv::Mat prev=gray(jf,C[0]);size_t h0=0,h1=0;std::vector<M>all,still,rot;for(size_t i=1;i<C.size();++i){cv::Mat cur=gray(jf,C[i]);if(prev.empty()||cur.empty()){prev=cur;continue;}std::vector<cv::Point2f>p0,p1;cv::goodFeaturesToTrack(prev,p0,350,.01,7,cv::noArray(),7);std::vector<uchar>st;std::vector<float>er;cv::calcOpticalFlowPyrLK(prev,cur,p0,p1,st,er,cv::Size(21,21),3);std::vector<cv::Point2f>q0,q1;for(size_t k=0;k<p0.size();++k)if(st[k]&&p1[k].x>=0&&p1[k].x<cur.cols&&p1[k].y>=0&&p1[k].y<cur.rows){q0.push_back(p0[k]);q1.push_back(p1[k]);}if(q0.size()<30){prev=cur;continue;}std::vector<cv::Point2f>u0,u1;cv::undistortPoints(q0,u0,K,D,cv::noArray(),K);cv::undistortPoints(q1,u1,K,D,cv::noArray(),K);cv::Mat mask,H=cv::findHomography(u0,u1,cv::RANSAC,1.5,mask,2000,.995);if(H.empty()){prev=cur;continue;}H.convertTo(H,CV_64F);cv::Mat Hn=Ki*H*K,Rbest=closestRotation(Hn),Hbest=K*Rbest*Ki;auto&a0=near(A,C[i-1].ts,h0);auto&a1=near(A,C[i].ts,h1);cv::Matx33d B0=rpy(a0.r,a0.p,a0.y),B1=rpy(a1.r,a1.p,a1.y);cv::Matx33d Rc=RBC.t()*B0.t()*B1*RBC; // inverse direction validated in v15.45b
cv::Mat Rfc(3,3,CV_64F,(void*)Rc.val);Rfc=Rfc.clone();cv::Mat Hfc=K*Rfc*Ki;std::vector<double>rf;for(size_t k=0;k<u0.size();++k)rf.push_back(cv::norm(u1[k]-u0[k]));M m;m.n=(int)u0.size();m.raw=med(rf);m.fc=reprojMed(u0,u1,Hfc);m.best=reprojMed(u0,u1,Hbest);m.herr=reprojMed(u0,u1,H,mask);m.hin=cv::countNonZero(mask)/(double)mask.total();m.fcrot=angle(Rfc);m.bestrot=angle(Rbest);bool turning=std::abs(.5*(a0.ys+a1.ys))*180/PI>2.0||m.fcrot>.08;all.push_back(m);(turning?rot:still).push_back(m);out<<C[i-1].ts<<','<<C[i].ts<<','<<(turning?1:0)<<','<<m.n<<','<<m.raw<<','<<m.fc<<','<<m.best<<','<<m.herr<<','<<m.hin<<','<<m.fcrot<<','<<m.bestrot<<'\n';prev=cur;}std::cout<<"============================================================\nJT-ZERO v15.47 HOMOGRAPHY vs PURE ROTATION\n============================================================\n";sum("STILL",still);sum("ROTATION",rot);sum("ALL",all);std::vector<double>b,h,f;for(auto&m:rot){b.push_back(m.best);h.push_back(m.herr);f.push_back(m.fc);}double bm=med(b),hm=med(h),fm=med(f);std::cout<<std::fixed<<std::setprecision(4)<<"ROTATION_FC_RESIDUAL_PX="<<fm<<"\nROTATION_BEST_PURE_ROT_RESIDUAL_PX="<<bm<<"\nROTATION_HOMOGRAPHY_RESIDUAL_PX="<<hm<<"\nBESTROT_TO_H_RATIO="<<(hm>1e-9?bm/hm:NAN)<<"\n";std::string v;if(rot.size()<30)v="INSUFFICIENT_ROTATION_DATA";else if(bm<=.35&&bm<=2.5*hm)v="VISUAL_MOTION_NEAR_PURE_ROTATION_FC_MODEL_MISMATCH";else if(bm<.65&&bm<.5*fm)v="MOSTLY_ROTATION_SMALL_PROJECTIVE_COMPONENT";else v="GENUINE_NON_ROTATIONAL_PROJECTIVE_COMPONENT_PRESENT";std::cout<<"V15_47_VERDICT="<<v<<"\nCSV="<<op<<"\nRESULT: COMPLETE\n";return 0;}catch(const std::exception&e){std::cerr<<"[FATAL] "<<e.what()<<"\n";return 1;}}