// JT-ZERO stationary HIGHRES_IMU noise characterization.
// Collects 60 s by default, computes mean/std/min/max and approximate white-noise density.
#define main jtzero_standstill_unused_main
#include "live_mono_imu_standstill.cpp"
#undef main

namespace {
struct AxisStats {
  uint64_t n=0; long double s=0,s2=0; double mn=1e300,mx=-1e300;
  void add(double x){++n;s+=x;s2+=(long double)x*x;mn=std::min(mn,x);mx=std::max(mx,x);}
  double mean()const{return n?(double)(s/n):0;}
  double stddev()const{if(n<2)return 0; long double m=s/n; long double v=(s2-n*m*m)/(n-1);return std::sqrt((double)std::max((long double)0,v));}
};
struct NoiseStats {AxisStats ax,ay,az,gx,gy,gz; uint64_t samples=0,nonmono=0,gaps20=0;int64_t prev=0;double dt_sum=0,dt_min=1e300,dt_max=0;uint64_t dt_n=0;
 void add(const mavlink_highres_imu_t&h){++samples;ax.add(h.xacc);ay.add(h.yacc);az.add(h.zacc);gx.add(h.xgyro);gy.add(h.ygyro);gz.add(h.zgyro);int64_t t=(int64_t)h.time_usec*1000LL;if(prev){double dt=(t-prev)/1e6;if(dt<=0)++nonmono;else{++dt_n;dt_sum+=dt;dt_min=std::min(dt_min,dt);dt_max=std::max(dt_max,dt);if(dt>20)++gaps20;}}prev=t;}
};
void printAxis(const char*name,const AxisStats&s,double fs){double nd=s.stddev()/std::sqrt(fs/2.0);std::cout<<std::setw(4)<<name<<" mean="<<std::setw(12)<<s.mean()<<" std="<<std::setw(12)<<s.stddev()<<" min="<<std::setw(12)<<s.mn<<" max="<<std::setw(12)<<s.mx<<" approx_density="<<nd<<"\n";}
}
int main(int argc,char**argv){google::InitGoogleLogging(argv[0]);double seconds=argc>1?std::max(20.0,std::atof(argv[1])):60.0;int fd=-1;uint8_t sys=0,comp=0;bool req=false;try{fd=openSerial();mavlink_status_t st{};mavlink_message_t msg{};std::cout<<"[MAV] waiting for HEARTBEAT...\n";int64_t dl=monotonicNs()+10000000000LL;while(monotonicNs()<dl&&!sys){pollfd q{fd,POLLIN,0};if(poll(&q,1,100)<=0)continue;uint8_t b[1024];ssize_t n=read(fd,b,sizeof(b));if(n<=0)continue;for(ssize_t i=0;i<n;i++)if(mavlink_parse_char(MAVLINK_COMM_0,b[i],&msg,&st)&&msg.msgid==MAVLINK_MSG_ID_HEARTBEAT){sys=msg.sysid;comp=msg.compid;break;}}if(!sys)throw std::runtime_error("HEARTBEAT timeout");requestRate(fd,sys,comp,MAVLINK_MSG_ID_HIGHRES_IMU,200);req=true;std::cout<<"[NOISE] Keep the complete rig absolutely motionless for "<<seconds<<" s.\n";NoiseStats s;int64_t end=monotonicNs()+(int64_t)(seconds*1e9);while(monotonicNs()<end){pollfd q{fd,POLLIN,0};if(poll(&q,1,20)<=0)continue;uint8_t b[4096];for(;;){ssize_t n=read(fd,b,sizeof(b));if(n==-1&&(errno==EAGAIN||errno==EWOULDBLOCK))break;if(n<=0)break;for(ssize_t i=0;i<n;i++)if(mavlink_parse_char(MAVLINK_COMM_0,b[i],&msg,&st)&&msg.msgid==MAVLINK_MSG_ID_HIGHRES_IMU){mavlink_highres_imu_t h{};mavlink_msg_highres_imu_decode(&msg,&h);s.add(h);}}}requestRate(fd,sys,comp,MAVLINK_MSG_ID_HIGHRES_IMU,0);req=false;close(fd);fd=-1;double mean_dt=s.dt_n?s.dt_sum/s.dt_n:5.0;double fs=1000.0/mean_dt;std::cout<<std::fixed<<std::setprecision(9)<<"\n============================================================\nJT-ZERO STATIONARY IMU NOISE RESULT\n============================================================\n"<<"duration: "<<seconds<<" s\nsamples: "<<s.samples<<"\nrate: "<<fs<<" Hz\ndt ms min/mean/max: "<<s.dt_min<<" / "<<mean_dt<<" / "<<s.dt_max<<"\nnonmonotonic: "<<s.nonmono<<" gaps>20ms: "<<s.gaps20<<"\n\nACCEL [m/s^2], approximate density [m/s^2/sqrt(Hz)]\n";printAxis("ax",s.ax,fs);printAxis("ay",s.ay,fs);printAxis("az",s.az,fs);std::cout<<"\nGYRO [rad/s], approximate density [rad/s/sqrt(Hz)]\n";printAxis("gx",s.gx,fs);printAxis("gy",s.gy,fs);printAxis("gz",s.gz,fs);std::cout<<"\nEurocMono reference currently inherited by JT-Zero:\naccel noise density = 0.002000000\ngyro noise density  = 0.000169680\nNOTE: approximate_density above is a short static white-noise estimate; random walk requires a longer Allan-deviation capture.\n";return 0;}catch(const std::exception&e){if(fd>=0&&req&&sys){try{requestRate(fd,sys,comp,MAVLINK_MSG_ID_HIGHRES_IMU,0);}catch(...){}}if(fd>=0)close(fd);std::cerr<<"[FATAL] "<<e.what()<<"\n";return 1;}}
